name:                parser-rest
version:             0.1.0.0
github:              "LinusSee/logfile-parser/tree/master/parser-rest"
license:             BSD3
author:              "Linus See"
maintainer:          "https://github.com/LinusSee"
copyright:           "2020 Linus See"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LinusSee/logfile-parser/tree/master/parser-rest#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- case-insensitive
- config-ini
- servant-server
- servant-multipart
- servant-options
- unordered-containers
- wai
- wai-cors
- wai-extra
- warp
- parsec
- text
- time

library:
  source-dirs:
    - src/business-logic
    - src/database/access
    - src/models
    - src/models/db
    - src/models/rest
    - src/orchestration
    - src/other/config
    - src/rest

executables:
  parser-rest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - parser-rest

tests:
  parser-rest-test:
    main:                Spec.hs
    source-dirs:
      - test
      - test/business-logic
      - test/rest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - parser-rest
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - QuickCheck
    - servant-quickcheck
    - servant-client
    - http-client
    - http-types
    - directory
    - time
